In [ ]:
# ============================================================
# INFORMATION RETRIEVAL (IR) - TF, IDF AND TF-IDF
# CELL 1: IMPORT REQUIRED LIBRARIES
# ============================================================

import re
import math
import pandas as pd
import numpy as np

from collections import Counter
from google.colab import files

# Stopwords
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

# Stemming
from nltk.stem import PorterStemmer

print("All required libraries imported successfully!")

All required libraries imported successfully!

In [ ]:
# ============================================================
# CELL 2: UPLOAD THE 5 TEXT DOCUMENTS
# ============================================================

print("Select your 5 social-media text files.")

uploaded = files.upload()

print("\nUploaded files:")
for filename in uploaded.keys():
    print("✓", filename)

print(f"\nTotal files uploaded: {len(uploaded)}")

Select your 5 social-media text files.

Saving social_communication.txt to social_communication.txt
Saving social_media_privacy_security.txt to social_media_privacy_security.txt
Saving social_media_education.txt to social_media_education.txt
Saving social_media_mental_health.txt to social_media_mental_health.txt
Saving social_media_marketing.txt to social_media_marketing.txt

Uploaded files:
✓ social_communication.txt
✓ social_media_privacy_security.txt
✓ social_media_education.txt
✓ social_media_mental_health.txt
✓ social_media_marketing.txt

Total files uploaded: 5

In [ ]:
# ============================================================
# CELL 3: READ AND CHECK THE 5 TEXT DOCUMENTS
# ============================================================

documents = {}

for filename in uploaded.keys():
    with open(filename, "r", encoding="utf-8") as file:
        documents[filename] = file.read()

print("=" * 70)
print("DOCUMENT COLLECTION")
print("=" * 70)

print(f"\nTotal documents: {len(documents)}")

for i, (filename, text) in enumerate(documents.items(), start=1):
    print(f"\nDocument {i}: {filename}")
    print(f"Number of characters: {len(text)}")
    print(f"Approximate number of words: {len(text.split())}")

    print("\nFirst 200 characters:")
    print(text[:200])
    print("-" * 70)

======================================================================
DOCUMENT COLLECTION
======================================================================

Total documents: 5

Document 1: social_communication.txt
Number of characters: 10216
Approximate number of words: 1346

First 200 characters:
Social media has transformed the way people communicate, interact, and share information in the modern world. Communication was once limited by geographical distance, time, and the availability of com
----------------------------------------------------------------------

Document 2: social_media_privacy_security.txt
Number of characters: 10642
Approximate number of words: 1466

First 200 characters:
Social media has become an important part of modern digital life, allowing people to communicate, share information, create content, and connect with communities around the world. Millions of users ac
----------------------------------------------------------------------

Document 3: social_media_education.txt
Number of characters: 10523
Approximate number of words: 1363

First 200 characters:
Social media has become an increasingly useful tool in the field of education. Platforms that were originally designed mainly for social communication are now being used by students, teachers, educati
----------------------------------------------------------------------

Document 4: social_media_mental_health.txt
Number of characters: 9770
Approximate number of words: 1369

First 200 characters:
Social media has become an important part of everyday life for millions of people. People use social media platforms to communicate with friends, follow news, watch videos, share photographs, particip
----------------------------------------------------------------------

Document 5: social_media_marketing.txt
Number of characters: 9920
Approximate number of words: 1357

First 200 characters:
Social media marketing has become an important part of modern business communication. The growth of social networking platforms has changed the way companies promote products, communicate with custome
----------------------------------------------------------------------

In [ ]:
# ============================================================
# CELL 4: PREPROCESSING
# ============================================================
# Steps:
# 1. Convert text to lowercase
# 2. Remove punctuation
# 3. Remove special characters
# 4. Remove extra spaces
# ============================================================

def preprocess_text(text):
    # Convert to lowercase
    text = text.lower()

    # Keep only English letters and spaces
    text = re.sub(r'[^a-z\s]', ' ', text)

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text


# Apply preprocessing to all 5 documents
preprocessed_documents = {}

for filename, text in documents.items():
    preprocessed_documents[filename] = preprocess_text(text)


# Display the results
print("=" * 70)
print("PREPROCESSING RESULTS")
print("=" * 70)

for filename in documents:

    print(f"\nDOCUMENT: {filename}")

    print("\nBefore preprocessing:")
    print(documents[filename][:300])

    print("\nAfter preprocessing:")
    print(preprocessed_documents[filename][:300])

    print("-" * 70)

print("\nPreprocessing completed successfully!")

======================================================================
PREPROCESSING RESULTS
======================================================================

DOCUMENT: social_communication.txt

Before preprocessing:
Social media has transformed the way people communicate, interact, and share information in the modern world. Communication was once limited by geographical distance, time, and the availability of communication technologies. People depended on letters, landline telephones, newspapers, and face-to-fa

After preprocessing:
social media has transformed the way people communicate interact and share information in the modern world communication was once limited by geographical distance time and the availability of communication technologies people depended on letters landline telephones newspapers and face to face conver
----------------------------------------------------------------------

DOCUMENT: social_media_privacy_security.txt

Before preprocessing:
Social media has become an important part of modern digital life, allowing people to communicate, share information, create content, and connect with communities around the world. Millions of users access social media platforms every day to exchange messages, upload photographs and videos, follow ne

After preprocessing:
social media has become an important part of modern digital life allowing people to communicate share information create content and connect with communities around the world millions of users access social media platforms every day to exchange messages upload photographs and videos follow news part
----------------------------------------------------------------------

DOCUMENT: social_media_education.txt

Before preprocessing:
Social media has become an increasingly useful tool in the field of education. Platforms that were originally designed mainly for social communication are now being used by students, teachers, educational institutions, researchers, and learning communities. The growth of digital communication has cr

After preprocessing:
social media has become an increasingly useful tool in the field of education platforms that were originally designed mainly for social communication are now being used by students teachers educational institutions researchers and learning communities the growth of digital communication has created
----------------------------------------------------------------------

DOCUMENT: social_media_mental_health.txt

Before preprocessing:
Social media has become an important part of everyday life for millions of people. People use social media platforms to communicate with friends, follow news, watch videos, share photographs, participate in communities, and express their opinions. While social media provides many benefits, its incre

After preprocessing:
social media has become an important part of everyday life for millions of people people use social media platforms to communicate with friends follow news watch videos share photographs participate in communities and express their opinions while social media provides many benefits its increasing us
----------------------------------------------------------------------

DOCUMENT: social_media_marketing.txt

Before preprocessing:
Social media marketing has become an important part of modern business communication. The growth of social networking platforms has changed the way companies promote products, communicate with customers, and build their brands. Traditional marketing depended heavily on newspapers, television, radio,

After preprocessing:
social media marketing has become an important part of modern business communication the growth of social networking platforms has changed the way companies promote products communicate with customers and build their brands traditional marketing depended heavily on newspapers television radio magazi
----------------------------------------------------------------------

Preprocessing completed successfully!

In [ ]:
# ============================================================
# CELL 5: TOKENIZATION
# ============================================================
# Tokenization means splitting the text into individual words.
# ============================================================

tokenized_documents = {}

for filename, text in preprocessed_documents.items():
    tokens = text.split()
    tokenized_documents[filename] = tokens


# Display tokenization results
print("=" * 70)
print("TOKENIZATION RESULTS")
print("=" * 70)

for filename, tokens in tokenized_documents.items():

    print(f"\nDOCUMENT: {filename}")
    print("Total tokens:", len(tokens))

    print("\nFirst 30 tokens:")
    print(tokens[:30])

    print("-" * 70)

print("\nTokenization completed successfully!")

======================================================================
TOKENIZATION RESULTS
======================================================================

DOCUMENT: social_communication.txt
Total tokens: 1356

First 30 tokens:
['social', 'media', 'has', 'transformed', 'the', 'way', 'people', 'communicate', 'interact', 'and', 'share', 'information', 'in', 'the', 'modern', 'world', 'communication', 'was', 'once', 'limited', 'by', 'geographical', 'distance', 'time', 'and', 'the', 'availability', 'of', 'communication', 'technologies']
----------------------------------------------------------------------

DOCUMENT: social_media_privacy_security.txt
Total tokens: 1475

First 30 tokens:
['social', 'media', 'has', 'become', 'an', 'important', 'part', 'of', 'modern', 'digital', 'life', 'allowing', 'people', 'to', 'communicate', 'share', 'information', 'create', 'content', 'and', 'connect', 'with', 'communities', 'around', 'the', 'world', 'millions', 'of', 'users', 'access']
----------------------------------------------------------------------

DOCUMENT: social_media_education.txt
Total tokens: 1369

First 30 tokens:
['social', 'media', 'has', 'become', 'an', 'increasingly', 'useful', 'tool', 'in', 'the', 'field', 'of', 'education', 'platforms', 'that', 'were', 'originally', 'designed', 'mainly', 'for', 'social', 'communication', 'are', 'now', 'being', 'used', 'by', 'students', 'teachers', 'educational']
----------------------------------------------------------------------

DOCUMENT: social_media_mental_health.txt
Total tokens: 1386

First 30 tokens:
['social', 'media', 'has', 'become', 'an', 'important', 'part', 'of', 'everyday', 'life', 'for', 'millions', 'of', 'people', 'people', 'use', 'social', 'media', 'platforms', 'to', 'communicate', 'with', 'friends', 'follow', 'news', 'watch', 'videos', 'share', 'photographs', 'participate']
----------------------------------------------------------------------

DOCUMENT: social_media_marketing.txt
Total tokens: 1362

First 30 tokens:
['social', 'media', 'marketing', 'has', 'become', 'an', 'important', 'part', 'of', 'modern', 'business', 'communication', 'the', 'growth', 'of', 'social', 'networking', 'platforms', 'has', 'changed', 'the', 'way', 'companies', 'promote', 'products', 'communicate', 'with', 'customers', 'and', 'build']
----------------------------------------------------------------------

Tokenization completed successfully!

In [ ]:
# ============================================================
# CELL 6: STOPWORD REMOVAL
# ============================================================
# Stopwords are common words that usually do not carry
# important meaning for Information Retrieval.
# ============================================================

stopword_removed_documents = {}

for filename, tokens in tokenized_documents.items():

    # Remove English stopwords
    filtered_tokens = [
        word for word in tokens
        if word not in ENGLISH_STOP_WORDS
    ]

    stopword_removed_documents[filename] = filtered_tokens


# Display results
print("=" * 70)
print("STOPWORD REMOVAL RESULTS")
print("=" * 70)

for filename in tokenized_documents:

    before = tokenized_documents[filename]
    after = stopword_removed_documents[filename]

    print(f"\nDOCUMENT: {filename}")

    print("Tokens before stopword removal:", len(before))
    print("Tokens after stopword removal :", len(after))

    print("\nFirst 30 tokens after stopword removal:")
    print(after[:30])

    print("-" * 70)

print("\nStopword removal completed successfully!")

======================================================================
STOPWORD REMOVAL RESULTS
======================================================================

DOCUMENT: social_communication.txt
Tokens before stopword removal: 1356
Tokens after stopword removal : 902

First 30 tokens after stopword removal:
['social', 'media', 'transformed', 'way', 'people', 'communicate', 'interact', 'share', 'information', 'modern', 'world', 'communication', 'limited', 'geographical', 'distance', 'time', 'availability', 'communication', 'technologies', 'people', 'depended', 'letters', 'landline', 'telephones', 'newspapers', 'face', 'face', 'conversations', 'exchange', 'information']
----------------------------------------------------------------------

DOCUMENT: social_media_privacy_security.txt
Tokens before stopword removal: 1475
Tokens after stopword removal : 950

First 30 tokens after stopword removal:
['social', 'media', 'important', 'modern', 'digital', 'life', 'allowing', 'people', 'communicate', 'share', 'information', 'create', 'content', 'connect', 'communities', 'world', 'millions', 'users', 'access', 'social', 'media', 'platforms', 'day', 'exchange', 'messages', 'upload', 'photographs', 'videos', 'follow', 'news']
----------------------------------------------------------------------

DOCUMENT: social_media_education.txt
Tokens before stopword removal: 1369
Tokens after stopword removal : 908

First 30 tokens after stopword removal:
['social', 'media', 'increasingly', 'useful', 'tool', 'field', 'education', 'platforms', 'originally', 'designed', 'mainly', 'social', 'communication', 'used', 'students', 'teachers', 'educational', 'institutions', 'researchers', 'learning', 'communities', 'growth', 'digital', 'communication', 'created', 'new', 'opportunities', 'sharing', 'knowledge', 'discussing']
----------------------------------------------------------------------

DOCUMENT: social_media_mental_health.txt
Tokens before stopword removal: 1386
Tokens after stopword removal : 868

First 30 tokens after stopword removal:
['social', 'media', 'important', 'everyday', 'life', 'millions', 'people', 'people', 'use', 'social', 'media', 'platforms', 'communicate', 'friends', 'follow', 'news', 'watch', 'videos', 'share', 'photographs', 'participate', 'communities', 'express', 'opinions', 'social', 'media', 'provides', 'benefits', 'increasing', 'use']
----------------------------------------------------------------------

DOCUMENT: social_media_marketing.txt
Tokens before stopword removal: 1362
Tokens after stopword removal : 871

First 30 tokens after stopword removal:
['social', 'media', 'marketing', 'important', 'modern', 'business', 'communication', 'growth', 'social', 'networking', 'platforms', 'changed', 'way', 'companies', 'promote', 'products', 'communicate', 'customers', 'build', 'brands', 'traditional', 'marketing', 'depended', 'heavily', 'newspapers', 'television', 'radio', 'magazines', 'billboards', 'direct']
----------------------------------------------------------------------

Stopword removal completed successfully!

In [ ]:
# ============================================================
# CELL 7: STEMMING
# ============================================================
# Stemming reduces words to their basic stem form.
# ============================================================

stemmer = PorterStemmer()

stemmed_documents = {}

for filename, tokens in stopword_removed_documents.items():

    stemmed_tokens = [
        stemmer.stem(word)
        for word in tokens
    ]

    stemmed_documents[filename] = stemmed_tokens


# Display stemming results
print("=" * 70)
print("STEMMING RESULTS")
print("=" * 70)

for filename in stopword_removed_documents:

    original_tokens = stopword_removed_documents[filename]
    stemmed_tokens = stemmed_documents[filename]

    print(f"\nDOCUMENT: {filename}")

    print("First 30 tokens before stemming:")
    print(original_tokens[:30])

    print("\nFirst 30 tokens after stemming:")
    print(stemmed_tokens[:30])

    print("-" * 70)


# ============================================================
# SHOW SOME STEMMING EXAMPLES
# ============================================================

print("\n" + "=" * 70)
print("STEMMING EXAMPLES")
print("=" * 70)

example_words = [
    "communication",
    "communicating",
    "communities",
    "connected",
    "marketing",
    "education",
    "educational",
    "security",
    "students",
    "learning"
]

for word in example_words:
    print(f"{word:20} → {stemmer.stem(word)}")


print("\nStemming completed successfully!")

======================================================================
STEMMING RESULTS
======================================================================

DOCUMENT: social_communication.txt
First 30 tokens before stemming:
['social', 'media', 'transformed', 'way', 'people', 'communicate', 'interact', 'share', 'information', 'modern', 'world', 'communication', 'limited', 'geographical', 'distance', 'time', 'availability', 'communication', 'technologies', 'people', 'depended', 'letters', 'landline', 'telephones', 'newspapers', 'face', 'face', 'conversations', 'exchange', 'information']

First 30 tokens after stemming:
['social', 'media', 'transform', 'way', 'peopl', 'commun', 'interact', 'share', 'inform', 'modern', 'world', 'commun', 'limit', 'geograph', 'distanc', 'time', 'avail', 'commun', 'technolog', 'peopl', 'depend', 'letter', 'landlin', 'telephon', 'newspap', 'face', 'face', 'convers', 'exchang', 'inform']
----------------------------------------------------------------------

DOCUMENT: social_media_privacy_security.txt
First 30 tokens before stemming:
['social', 'media', 'important', 'modern', 'digital', 'life', 'allowing', 'people', 'communicate', 'share', 'information', 'create', 'content', 'connect', 'communities', 'world', 'millions', 'users', 'access', 'social', 'media', 'platforms', 'day', 'exchange', 'messages', 'upload', 'photographs', 'videos', 'follow', 'news']

First 30 tokens after stemming:
['social', 'media', 'import', 'modern', 'digit', 'life', 'allow', 'peopl', 'commun', 'share', 'inform', 'creat', 'content', 'connect', 'commun', 'world', 'million', 'user', 'access', 'social', 'media', 'platform', 'day', 'exchang', 'messag', 'upload', 'photograph', 'video', 'follow', 'news']
----------------------------------------------------------------------

DOCUMENT: social_media_education.txt
First 30 tokens before stemming:
['social', 'media', 'increasingly', 'useful', 'tool', 'field', 'education', 'platforms', 'originally', 'designed', 'mainly', 'social', 'communication', 'used', 'students', 'teachers', 'educational', 'institutions', 'researchers', 'learning', 'communities', 'growth', 'digital', 'communication', 'created', 'new', 'opportunities', 'sharing', 'knowledge', 'discussing']

First 30 tokens after stemming:
['social', 'media', 'increasingli', 'use', 'tool', 'field', 'educ', 'platform', 'origin', 'design', 'mainli', 'social', 'commun', 'use', 'student', 'teacher', 'educ', 'institut', 'research', 'learn', 'commun', 'growth', 'digit', 'commun', 'creat', 'new', 'opportun', 'share', 'knowledg', 'discuss']
----------------------------------------------------------------------

DOCUMENT: social_media_mental_health.txt
First 30 tokens before stemming:
['social', 'media', 'important', 'everyday', 'life', 'millions', 'people', 'people', 'use', 'social', 'media', 'platforms', 'communicate', 'friends', 'follow', 'news', 'watch', 'videos', 'share', 'photographs', 'participate', 'communities', 'express', 'opinions', 'social', 'media', 'provides', 'benefits', 'increasing', 'use']

First 30 tokens after stemming:
['social', 'media', 'import', 'everyday', 'life', 'million', 'peopl', 'peopl', 'use', 'social', 'media', 'platform', 'commun', 'friend', 'follow', 'news', 'watch', 'video', 'share', 'photograph', 'particip', 'commun', 'express', 'opinion', 'social', 'media', 'provid', 'benefit', 'increas', 'use']
----------------------------------------------------------------------

DOCUMENT: social_media_marketing.txt
First 30 tokens before stemming:
['social', 'media', 'marketing', 'important', 'modern', 'business', 'communication', 'growth', 'social', 'networking', 'platforms', 'changed', 'way', 'companies', 'promote', 'products', 'communicate', 'customers', 'build', 'brands', 'traditional', 'marketing', 'depended', 'heavily', 'newspapers', 'television', 'radio', 'magazines', 'billboards', 'direct']

First 30 tokens after stemming:
['social', 'media', 'market', 'import', 'modern', 'busi', 'commun', 'growth', 'social', 'network', 'platform', 'chang', 'way', 'compani', 'promot', 'product', 'commun', 'custom', 'build', 'brand', 'tradit', 'market', 'depend', 'heavili', 'newspap', 'televis', 'radio', 'magazin', 'billboard', 'direct']
----------------------------------------------------------------------

======================================================================
STEMMING EXAMPLES
======================================================================
communication        → commun
communicating        → commun
communities          → commun
connected            → connect
marketing            → market
education            → educ
educational          → educ
security             → secur
students             → student
learning             → learn

Stemming completed successfully!

In [ ]:
# ============================================================
# CELL 8: TERM FREQUENCY (TF)
# ============================================================
# TF = Number of occurrences of a term
#      --------------------------------
#      Total number of terms in document
# ============================================================

tf_documents = {}

for filename, tokens in stemmed_documents.items():

    # Count how many times each term occurs
    term_counts = Counter(tokens)

    # Total number of terms in the document
    total_terms = len(tokens)

    # Calculate TF for every term
    tf_values = {}

    for term, count in term_counts.items():
        tf_values[term] = count / total_terms

    tf_documents[filename] = tf_values


# ============================================================
# CREATE A COMPLETE TF TABLE
# ============================================================

# Get all unique terms from all 5 documents
all_terms = sorted(
    set(
        term
        for document in tf_documents.values()
        for term in document.keys()
    )
)

# Create DataFrame
tf_table = pd.DataFrame(index=all_terms)

for filename in tf_documents:
    tf_table[filename] = [
        tf_documents[filename].get(term, 0)
        for term in all_terms
    ]


# ============================================================
# DISPLAY TF RESULTS
# ============================================================

print("=" * 70)
print("TERM FREQUENCY (TF)")
print("=" * 70)

print("\nFormula:")
print("TF = Number of occurrences of term / Total number of terms")

print("\nTotal number of unique terms:", len(all_terms))

print("\nComplete TF Table:")
display(tf_table.round(6))


# ============================================================
# TOP 20 TERMS BY TF FOR EACH DOCUMENT
# ============================================================

print("\n" + "=" * 70)
print("TOP 20 TERMS BY TF")
print("=" * 70)

for filename, tf_values in tf_documents.items():

    top_terms = sorted(
        tf_values.items(),
        key=lambda x: x[1],
        reverse=True
    )[:20]

    print(f"\nDOCUMENT: {filename}")
    print("-" * 50)

    for rank, (term, tf_value) in enumerate(top_terms, start=1):
        print(f"{rank:2}. {term:20} TF = {tf_value:.6f}")


print("\nTF calculation completed successfully!")

======================================================================
TERM FREQUENCY (TF)
======================================================================

Formula:
TF = Number of occurrences of term / Total number of terms

Total number of unique terms: 816

Complete TF Table:

,social_communication.txt,social_media_privacy_security.txt,social_media_education.txt,social_media_mental_health.txt,social_media_marketing.txt
abbrevi,0.001109,0.000000,0.000000,0.000000,0.000000
abil,0.001109,0.000000,0.000000,0.003456,0.002296
abl,0.000000,0.002105,0.001101,0.000000,0.000000
abus,0.001109,0.001053,0.000000,0.000000,0.000000
academ,0.002217,0.000000,0.017621,0.001152,0.000000
...,...,...,...,...,...
written,0.001109,0.000000,0.000000,0.000000,0.000000
x,0.001109,0.000000,0.000000,0.000000,0.001148
young,0.000000,0.003158,0.000000,0.002304,0.000000
younger,0.000000,0.001053,0.000000,0.001152,0.000000
youtub,0.001109,0.000000,0.000000,0.000000,0.001148

======================================================================
TOP 20 TERMS BY TF
======================================================================

DOCUMENT: social_communication.txt
--------------------------------------------------
 1. commun               TF = 0.064302
 2. social               TF = 0.034368
 3. media                TF = 0.031042
 4. inform               TF = 0.025499
 5. peopl                TF = 0.021064
 6. share                TF = 0.019956
 7. use                  TF = 0.019956
 8. user                 TF = 0.018847
 9. onlin                TF = 0.015521
10. platform             TF = 0.011086
11. import               TF = 0.011086
12. interact             TF = 0.008869
13. creat                TF = 0.008869
14. messag               TF = 0.008869
15. video                TF = 0.008869
16. convers              TF = 0.007761
17. person               TF = 0.007761
18. differ               TF = 0.007761
19. digit                TF = 0.007761
20. profession           TF = 0.007761

DOCUMENT: social_media_privacy_security.txt
--------------------------------------------------
 1. user                 TF = 0.049474
 2. inform               TF = 0.035789
 3. social               TF = 0.021053
 4. media                TF = 0.020000
 5. use                  TF = 0.020000
 6. account              TF = 0.020000
 7. secur                TF = 0.018947
 8. share                TF = 0.015789
 9. privaci              TF = 0.015789
10. person               TF = 0.015789
11. password             TF = 0.013684
12. creat                TF = 0.011579
13. platform             TF = 0.011579
14. digit                TF = 0.010526
15. commun               TF = 0.010526
16. provid               TF = 0.010526
17. import               TF = 0.009474
18. access               TF = 0.009474
19. messag               TF = 0.009474
20. onlin                TF = 0.009474

DOCUMENT: social_media_education.txt
--------------------------------------------------
 1. student              TF = 0.057269
 2. educ                 TF = 0.040749
 3. social               TF = 0.033040
 4. media                TF = 0.030837
 5. commun               TF = 0.030837
 6. use                  TF = 0.028634
 7. inform               TF = 0.018722
 8. academ               TF = 0.017621
 9. teacher              TF = 0.015419
10. learn                TF = 0.014317
11. onlin                TF = 0.014317
12. institut             TF = 0.012115
13. creat                TF = 0.012115
14. opportun             TF = 0.012115
15. video                TF = 0.012115
16. share                TF = 0.011013
17. platform             TF = 0.009912
18. access               TF = 0.009912
19. import               TF = 0.009912
20. digit                TF = 0.008811

DOCUMENT: social_media_mental_health.txt
--------------------------------------------------
 1. social               TF = 0.046083
 2. media                TF = 0.034562
 3. user                 TF = 0.028802
 4. onlin                TF = 0.021889
 5. use                  TF = 0.019585
 6. peopl                TF = 0.018433
 7. commun               TF = 0.017281
 8. help                 TF = 0.016129
 9. content              TF = 0.012673
10. provid               TF = 0.011521
11. emot                 TF = 0.011521
12. time                 TF = 0.011521
13. person               TF = 0.010369
14. educ                 TF = 0.009217
15. inform               TF = 0.009217
16. comment              TF = 0.009217
17. neg                  TF = 0.009217
18. platform             TF = 0.008065
19. video                TF = 0.008065
20. share                TF = 0.008065

DOCUMENT: social_media_marketing.txt
--------------------------------------------------
 1. social               TF = 0.039036
 2. busi                 TF = 0.037887
 3. market               TF = 0.036739
 4. media                TF = 0.034443
 5. compani              TF = 0.033295
 6. custom               TF = 0.033295
 7. content              TF = 0.022962
 8. product              TF = 0.020666
 9. commun               TF = 0.017222
10. user                 TF = 0.017222
11. audienc              TF = 0.016073
12. brand                TF = 0.014925
13. use                  TF = 0.014925
14. platform             TF = 0.013777
15. advertis             TF = 0.012629
16. creat                TF = 0.012629
17. help                 TF = 0.010333
18. promot               TF = 0.009185
19. provid               TF = 0.008037
20. reach                TF = 0.008037

TF calculation completed successfully!

In [ ]:
# ============================================================
# CELL 9: DOCUMENT FREQUENCY (DF)
# ============================================================
# DF = Number of documents containing a particular term
# ============================================================

df_values = {}

# Total number of documents
N = len(stemmed_documents)

# Calculate DF for every term
for term in all_terms:

    document_count = 0

    for tokens in stemmed_documents.values():

        # Check whether the term appears in the document
        if term in set(tokens):
            document_count += 1

    df_values[term] = document_count


# ============================================================
# CREATE DF TABLE
# ============================================================

df_table = pd.DataFrame(
    list(df_values.items()),
    columns=["Term", "DF"]
)

# Sort by DF from highest to lowest
df_table = df_table.sort_values(
    by="DF",
    ascending=False
).reset_index(drop=True)


# ============================================================
# DISPLAY DF RESULTS
# ============================================================

print("=" * 70)
print("DOCUMENT FREQUENCY (DF)")
print("=" * 70)

print("\nNumber of documents (N):", N)

print("\nFormula:")
print("DF(term) = Number of documents containing the term")

print("\nComplete DF Table:")
display(df_table)


# ============================================================
# SHOW SOME EXAMPLES
# ============================================================

print("\n" + "=" * 70)
print("DF EXAMPLES")
print("=" * 70)

for _, row in df_table.head(20).iterrows():
    print(f"{row['Term']:20} → DF = {row['DF']}")


print("\nDF calculation completed successfully!")

======================================================================
DOCUMENT FREQUENCY (DF)
======================================================================

Number of documents (N): 5

Formula:
DF(term) = Number of documents containing the term

Complete DF Table:

           Term  DF
0      interact   5
1    understand   5
2       instead   5
3      interest   5
4        inform   5
..          ...  ..
811       layer   1
812      launch   1
813        late   1
814     landlin   1
815        lack   1

[816 rows x 2 columns]

======================================================================
DF EXAMPLES
======================================================================
interact             → DF = 5
understand           → DF = 5
instead              → DF = 5
interest             → DF = 5
inform               → DF = 5
avail                → DF = 5
time                 → DF = 5
live                 → DF = 5
studi                → DF = 5
awar                 → DF = 5
avoid                → DF = 5
care                 → DF = 5
maintain             → DF = 5
make                 → DF = 5
major                → DF = 5
social               → DF = 5
group                → DF = 5
messag               → DF = 5
media                → DF = 5
new                  → DF = 5

DF calculation completed successfully!

In [ ]:
# ============================================================
# CELL 10: INVERSE DOCUMENT FREQUENCY (IDF)
# ============================================================
# IDF = log(N / DF)
#
# N  = Total number of documents
# DF = Number of documents containing the term
# ============================================================

# N is already calculated in Cell 9
print("Total number of documents (N):", N)


# ============================================================
# CALCULATE IDF FOR EVERY TERM
# ============================================================

idf_values = {}

for term in all_terms:

    df = df_values[term]

    # IDF formula
    idf = math.log(N / df)

    idf_values[term] = idf


# ============================================================
# CREATE IDF TABLE
# ============================================================

idf_table = pd.DataFrame(
    [
        [term, df_values[term], idf_values[term]]
        for term in all_terms
    ],
    columns=["Term", "DF", "IDF"]
)

# Sort by IDF from highest to lowest
idf_table = idf_table.sort_values(
    by="IDF",
    ascending=False
).reset_index(drop=True)


# ============================================================
# DISPLAY IDF RESULTS
# ============================================================

print("\n" + "=" * 70)
print("INVERSE DOCUMENT FREQUENCY (IDF)")
print("=" * 70)

print("\nFormula:")
print("IDF = log(N / DF)")

print("\nWhere:")
print("N =", N)
print("DF = Number of documents containing the term")

print("\nComplete IDF Table:")
display(idf_table.round(6))


# ============================================================
# SHOW IDF EXAMPLES
# ============================================================

print("\n" + "=" * 70)
print("IDF EXAMPLES")
print("=" * 70)

for _, row in idf_table.head(20).iterrows():

    term = row["Term"]
    df = int(row["DF"])
    idf = row["IDF"]

    print(
        f"{term:20} → "
        f"DF = {df} → "
        f"IDF = log({N}/{df}) = {idf:.6f}"
    )


# ============================================================
# IMPORTANT OBSERVATION
# ============================================================

print("\n" + "=" * 70)
print("IMPORTANT IDF OBSERVATION")
print("=" * 70)

print("""
If a term appears in all 5 documents:

IDF = log(5 / 5)
    = log(1)
    = 0

Therefore, terms appearing in many documents
have lower IDF.

Terms appearing in fewer documents
have higher IDF.
""")


print("\nIDF calculation completed successfully!")

Total number of documents (N): 5

======================================================================
INVERSE DOCUMENT FREQUENCY (IDF)
======================================================================

Formula:
IDF = log(N / DF)

Where:
N = 5
DF = Number of documents containing the term

Complete IDF Table:

           Term  DF       IDF
0          warn   1  1.609438
1          want   1  1.609438
2        vulner   1  1.609438
3          voic   1  1.609438
4    vocabulari   1  1.609438
..          ...  ..       ...
811       avail   5  0.000000
812       avoid   5  0.000000
813        awar   5  0.000000
814         use   5  0.000000
815        user   5  0.000000

[816 rows x 3 columns]

======================================================================
IDF EXAMPLES
======================================================================
warn                 → DF = 1 → IDF = log(5/1) = 1.609438
want                 → DF = 1 → IDF = log(5/1) = 1.609438
vulner               → DF = 1 → IDF = log(5/1) = 1.609438
voic                 → DF = 1 → IDF = log(5/1) = 1.609438
vocabulari           → DF = 1 → IDF = log(5/1) = 1.609438
visit                → DF = 1 → IDF = log(5/1) = 1.609438
victim               → DF = 1 → IDF = log(5/1) = 1.609438
verif                → DF = 1 → IDF = log(5/1) = 1.609438
anim                 → DF = 1 → IDF = log(5/1) = 1.609438
analyz               → DF = 1 → IDF = log(5/1) = 1.609438
analysi              → DF = 1 → IDF = log(5/1) = 1.609438
algorithm            → DF = 1 → IDF = log(5/1) = 1.609438
alarm                → DF = 1 → IDF = log(5/1) = 1.609438
aggress              → DF = 1 → IDF = log(5/1) = 1.609438
age                  → DF = 1 → IDF = log(5/1) = 1.609438
admiss               → DF = 1 → IDF = log(5/1) = 1.609438
adjust               → DF = 1 → IDF = log(5/1) = 1.609438
address              → DF = 1 → IDF = log(5/1) = 1.609438
aspect               → DF = 1 → IDF = log(5/1) = 1.609438
art                  → DF = 1 → IDF = log(5/1) = 1.609438

======================================================================
IMPORTANT IDF OBSERVATION
======================================================================

If a term appears in all 5 documents:

IDF = log(5 / 5)
    = log(1)
    = 0

Therefore, terms appearing in many documents
have lower IDF.

Terms appearing in fewer documents
have higher IDF.


IDF calculation completed successfully!

In [ ]:
# ============================================================
# CELL 11: TF-IDF CALCULATION
# ============================================================
# TF-IDF = TF × IDF
#
# TF  → calculated in Cell 8
# IDF → calculated in Cell 10
# ============================================================

tfidf_table = pd.DataFrame(index=all_terms)

# Calculate TF-IDF for every term in every document
for filename in stemmed_documents:

    tfidf_values = []

    for term in all_terms:

        # Get TF value
        tf = tf_documents[filename].get(term, 0)

        # Get IDF value
        idf = idf_values[term]

        # TF-IDF formula
        tfidf = tf * idf

        tfidf_values.append(tfidf)

    tfidf_table[filename] = tfidf_values


# ============================================================
# DISPLAY COMPLETE TF-IDF TABLE
# ============================================================

print("=" * 70)
print("TF-IDF RESULTS")
print("=" * 70)

print("\nFormula:")
print("TF-IDF = TF × IDF")

print("\nComplete TF-IDF Table:")
display(tfidf_table.round(6))


# ============================================================
# TOP 10 TF-IDF TERMS FOR EACH DOCUMENT
# ============================================================

print("\n" + "=" * 70)
print("TOP 10 TF-IDF TERMS FOR EACH DOCUMENT")
print("=" * 70)

for filename in stemmed_documents:

    top_terms = (
        tfidf_table[filename]
        .sort_values(ascending=False)
        .head(10)
    )

    print(f"\nDOCUMENT: {filename}")
    print("-" * 50)

    for rank, (term, score) in enumerate(top_terms.items(), start=1):

        print(
            f"{rank:2}. {term:20} "
            f"TF-IDF = {score:.6f}"
        )


print("\nTF-IDF calculation completed successfully!")

======================================================================
TF-IDF RESULTS
======================================================================

Formula:
TF-IDF = TF × IDF

Complete TF-IDF Table:

,social_communication.txt,social_media_privacy_security.txt,social_media_education.txt,social_media_mental_health.txt,social_media_marketing.txt
abbrevi,0.001784,0.000000,0.000000,0.000000,0.000000
abil,0.000566,0.000000,0.000000,0.001766,0.001173
abl,0.000000,0.001929,0.001009,0.000000,0.000000
abus,0.001016,0.000965,0.000000,0.000000,0.000000
academ,0.001133,0.000000,0.009001,0.000589,0.000000
...,...,...,...,...,...
written,0.001784,0.000000,0.000000,0.000000,0.000000
x,0.001016,0.000000,0.000000,0.000000,0.001052
young,0.000000,0.002894,0.000000,0.002111,0.000000
younger,0.000000,0.000965,0.000000,0.001056,0.000000
youtub,0.001016,0.000000,0.000000,0.000000,0.001052

======================================================================
TOP 10 TF-IDF TERMS FOR EACH DOCUMENT
======================================================================

DOCUMENT: social_communication.txt
--------------------------------------------------
 1. emoji                TF-IDF = 0.008921
 2. text                 TF-IDF = 0.007137
 3. multimedia           TF-IDF = 0.005353
 4. call                 TF-IDF = 0.005353
 5. voic                 TF-IDF = 0.005353
 6. distanc              TF-IDF = 0.005353
 7. physic               TF-IDF = 0.004063
 8. event                TF-IDF = 0.004063
 9. convers              TF-IDF = 0.003964
10. instantli            TF-IDF = 0.003569

DOCUMENT: social_media_privacy_security.txt
--------------------------------------------------
 1. secur                TF-IDF = 0.009679
 2. attack               TF-IDF = 0.008471
 3. password             TF-IDF = 0.006990
 4. reveal               TF-IDF = 0.006777
 5. verif                TF-IDF = 0.006777
 6. scam                 TF-IDF = 0.006777
 7. softwar              TF-IDF = 0.005082
 8. cautiou              TF-IDF = 0.005082
 9. applic               TF-IDF = 0.005082
10. unfamiliar           TF-IDF = 0.005082

DOCUMENT: social_media_education.txt
--------------------------------------------------
 1. student              TF-IDF = 0.012779
 2. academ               TF-IDF = 0.009001
 3. research             TF-IDF = 0.008863
 4. learner              TF-IDF = 0.008863
 5. classroom            TF-IDF = 0.007090
 6. concept              TF-IDF = 0.007090
 7. explan               TF-IDF = 0.007090
 8. distract             TF-IDF = 0.005318
 9. engin                TF-IDF = 0.005318
10. scienc               TF-IDF = 0.005318

DOCUMENT: social_media_mental_health.txt
--------------------------------------------------
 1. sleep                TF-IDF = 0.012979
 2. feel                 TF-IDF = 0.011125
 3. emot                 TF-IDF = 0.010556
 4. stress               TF-IDF = 0.007417
 5. mental               TF-IDF = 0.007417
 6. comparison           TF-IDF = 0.007417
 7. cyberbulli           TF-IDF = 0.006334
 8. posit                TF-IDF = 0.006334
 9. confid               TF-IDF = 0.005563
10. health               TF-IDF = 0.005563

DOCUMENT: social_media_marketing.txt
--------------------------------------------------
 1. market               TF-IDF = 0.059130
 2. brand                TF-IDF = 0.024021
 3. custom               TF-IDF = 0.017008
 4. campaign             TF-IDF = 0.012935
 5. perform              TF-IDF = 0.009239
 6. busi                 TF-IDF = 0.008454
 7. compani              TF-IDF = 0.007430
 8. launch               TF-IDF = 0.007391
 9. strategi             TF-IDF = 0.007391
10. target               TF-IDF = 0.006312

TF-IDF calculation completed successfully!

In [ ]:
# ============================================================
# CELL 12: USER QUERY PROCESSING
# ============================================================

print("=" * 70)
print("INFORMATION RETRIEVAL - QUERY")
print("=" * 70)

# Ask the user to enter a search query
query = input("\nEnter your search query: ")

print("\nOriginal Query:")
print(query)


# ============================================================
# PREPROCESS THE QUERY
# ============================================================

# Lowercase
query_processed = query.lower()

# Remove punctuation and special characters
query_processed = re.sub(r'[^a-z\s]', ' ', query_processed)

# Remove extra spaces
query_processed = re.sub(r'\s+', ' ', query_processed).strip()


# ============================================================
# TOKENIZATION
# ============================================================

query_tokens = query_processed.split()


# ============================================================
# STOPWORD REMOVAL
# ============================================================

query_without_stopwords = [
    word for word in query_tokens
    if word not in ENGLISH_STOP_WORDS
]


# ============================================================
# STEMMING
# ============================================================

query_stemmed = [
    stemmer.stem(word)
    for word in query_without_stopwords
]


# ============================================================
# DISPLAY QUERY PROCESSING
# ============================================================

print("\n" + "=" * 70)
print("QUERY PROCESSING")
print("=" * 70)

print("\nOriginal Query:")
print(query)

print("\nAfter Preprocessing:")
print(query_processed)

print("\nAfter Tokenization:")
print(query_tokens)

print("\nAfter Stopword Removal:")
print(query_without_stopwords)

print("\nAfter Stemming:")
print(query_stemmed)

print("\nQuery processing completed successfully!")

======================================================================
INFORMATION RETRIEVAL - QUERY
======================================================================

Enter your search query: privacy security social media

Original Query:
privacy security social media

======================================================================
QUERY PROCESSING
======================================================================

Original Query:
privacy security social media

After Preprocessing:
privacy security social media

After Tokenization:
['privacy', 'security', 'social', 'media']

After Stopword Removal:
['privacy', 'security', 'social', 'media']

After Stemming:
['privaci', 'secur', 'social', 'media']

Query processing completed successfully!

In [ ]:
# ============================================================
# CELL 13: QUERY TF AND QUERY TF-IDF
# ============================================================

print("=" * 70)
print("QUERY TF AND QUERY TF-IDF")
print("=" * 70)

# ------------------------------------------------------------
# 1. Calculate Query TF
# ------------------------------------------------------------

query_term_counts = Counter(query_stemmed)

# Total number of terms in the processed query
query_total_terms = len(query_stemmed)

query_tf = {}

if query_total_terms > 0:

    for term, count in query_term_counts.items():
        query_tf[term] = count / query_total_terms

else:
    print("The query contains no valid terms.")


# ------------------------------------------------------------
# 2. Calculate Query TF-IDF
# ------------------------------------------------------------

query_tfidf = {}

for term, tf in query_tf.items():

    # Use IDF calculated from the 5 documents
    if term in idf_values:
        idf = idf_values[term]
    else:
        # If the query term does not occur in any document,
        # its document frequency is 0 and we assign IDF = 0
        idf = 0

    # TF-IDF = TF × IDF
    query_tfidf[term] = tf * idf


# ------------------------------------------------------------
# 3. Display Query TF
# ------------------------------------------------------------

print("\nQuery:")
print(query)

print("\nProcessed Query:")
print(query_stemmed)

print("\nQuery TF:")
print("-" * 50)

for term, value in query_tf.items():
    print(f"{term:20} TF = {value:.6f}")


# ------------------------------------------------------------
# 4. Display Query TF-IDF
# ------------------------------------------------------------

print("\nQuery TF-IDF:")
print("-" * 50)

for term, value in query_tfidf.items():
    print(f"{term:20} TF-IDF = {value:.6f}")


print("\nQuery TF and Query TF-IDF calculated successfully!")

======================================================================
QUERY TF AND QUERY TF-IDF
======================================================================

Query:
privacy security social media

Processed Query:
['privaci', 'secur', 'social', 'media']

Query TF:
--------------------------------------------------
privaci              TF = 0.250000
secur                TF = 0.250000
social               TF = 0.250000
media                TF = 0.250000

Query TF-IDF:
--------------------------------------------------
privaci              TF-IDF = 0.000000
secur                TF-IDF = 0.127706
social               TF-IDF = 0.000000
media                TF-IDF = 0.000000

Query TF and Query TF-IDF calculated successfully!

In [ ]:
# ============================================================
# CELL 14: COSINE SIMILARITY AND DOCUMENT RANKING
# ============================================================

print("=" * 70)
print("COSINE SIMILARITY - DOCUMENT RETRIEVAL")
print("=" * 70)


# ------------------------------------------------------------
# 1. Create the Query TF-IDF Vector
# ------------------------------------------------------------

query_vector = np.array([
    query_tfidf.get(term, 0)
    for term in all_terms
])


# ------------------------------------------------------------
# 2. Calculate Cosine Similarity
#    between Query and each Document
# ------------------------------------------------------------

similarity_results = {}

for filename in tfidf_table.columns:

    # Get the document TF-IDF vector
    document_vector = tfidf_table[filename].values

    # Calculate dot product
    dot_product = np.dot(query_vector, document_vector)

    # Calculate magnitudes
    query_magnitude = np.linalg.norm(query_vector)
    document_magnitude = np.linalg.norm(document_vector)

    # Avoid division by zero
    if query_magnitude == 0 or document_magnitude == 0:
        similarity = 0
    else:
        similarity = (
            dot_product /
            (query_magnitude * document_magnitude)
        )

    similarity_results[filename] = similarity


# ------------------------------------------------------------
# 3. Rank Documents
# ------------------------------------------------------------

ranked_results = sorted(
    similarity_results.items(),
    key=lambda x: x[1],
    reverse=True
)


# ------------------------------------------------------------
# 4. Display Results
# ------------------------------------------------------------

print("\nQuery:")
print(query)

print("\nProcessed Query:")
print(query_stemmed)

print("\n" + "=" * 70)
print("SEARCH RESULTS")
print("=" * 70)

for rank, (filename, score) in enumerate(ranked_results, start=1):

    print(
        f"\nRank {rank}: {filename}"
    )

    print(
        f"Cosine Similarity: {score:.6f}"
    )


# ------------------------------------------------------------
# 5. Display Most Relevant Document
# ------------------------------------------------------------

most_relevant_document = ranked_results[0][0]
highest_score = ranked_results[0][1]

print("\n" + "=" * 70)
print("MOST RELEVANT DOCUMENT")
print("=" * 70)

print("\nQuery:", query)

print("Document:", most_relevant_document)

print(f"Similarity Score: {highest_score:.6f}")


# ------------------------------------------------------------
# 6. Create a Ranking Table
# ------------------------------------------------------------

ranking_table = pd.DataFrame(
    ranked_results,
    columns=["Document", "Cosine Similarity"]
)

ranking_table.insert(
    0,
    "Rank",
    range(1, len(ranking_table) + 1)
)

print("\n" + "=" * 70)
print("DOCUMENT RANKING TABLE")
print("=" * 70)

display(ranking_table.round(6))


print("\nDocument retrieval completed successfully!")

======================================================================
COSINE SIMILARITY - DOCUMENT RETRIEVAL
======================================================================

Query:
privacy security social media

Processed Query:
['privaci', 'secur', 'social', 'media']

======================================================================
SEARCH RESULTS
======================================================================

Rank 1: social_media_privacy_security.txt
Cosine Similarity: 0.259137

Rank 2: social_communication.txt
Cosine Similarity: 0.056908

Rank 3: social_media_education.txt
Cosine Similarity: 0.047003

Rank 4: social_media_mental_health.txt
Cosine Similarity: 0.000000

Rank 5: social_media_marketing.txt
Cosine Similarity: 0.000000

======================================================================
MOST RELEVANT DOCUMENT
======================================================================

Query: privacy security social media
Document: social_media_privacy_security.txt
Similarity Score: 0.259137

======================================================================
DOCUMENT RANKING TABLE
======================================================================

   Rank                           Document  Cosine Similarity
0     1  social_media_privacy_security.txt           0.259137
1     2           social_communication.txt           0.056908
2     3         social_media_education.txt           0.047003
3     4     social_media_mental_health.txt           0.000000
4     5         social_media_marketing.txt           0.000000

Document retrieval completed successfully!

In [ ]:
# ============================================================
# CELL 15: FINAL IR SUMMARY AND CONCLUSION
# ============================================================

print("\n")
print("=" * 80)
print("              INFORMATION RETRIEVAL SYSTEM")
print("              FINAL SUMMARY")
print("=" * 80)

print("\n1. DOCUMENT COLLECTION")
print("-" * 80)
print(f"Number of documents processed: {len(documents)}")

for i, filename in enumerate(documents.keys(), start=1):
    print(f"{i}. {filename}")


print("\n2. PREPROCESSING")
print("-" * 80)
print("✓ Lowercase conversion")
print("✓ Punctuation and special-character removal")
print("✓ Extra-space removal")


print("\n3. TOKENIZATION")
print("-" * 80)
print("✓ Documents divided into individual words")


print("\n4. STOPWORD REMOVAL")
print("-" * 80)
print("✓ Common English stopwords removed")


print("\n5. STEMMING")
print("-" * 80)
print("✓ Words converted to their stem forms using Porter Stemmer")


print("\n6. TERM FREQUENCY (TF)")
print("-" * 80)
print("Formula:")
print("TF = Number of occurrences of term / Total number of terms")
print("✓ TF calculated manually for all documents")


print("\n7. DOCUMENT FREQUENCY (DF)")
print("-" * 80)
print("Formula:")
print("DF = Number of documents containing the term")
print("✓ DF calculated for all terms")


print("\n8. INVERSE DOCUMENT FREQUENCY (IDF)")
print("-" * 80)
print("Formula:")
print("IDF = log(N / DF)")
print(f"Where N = {N}")
print("✓ IDF calculated manually")


print("\n9. TF-IDF")
print("-" * 80)
print("Formula:")
print("TF-IDF = TF × IDF")
print("✓ TF-IDF calculated manually for all 5 documents")


print("\n10. USER QUERY")
print("-" * 80)
print("Original Query:")
print(query)

print("\nProcessed Query:")
print(query_stemmed)


print("\n11. DOCUMENT RETRIEVAL")
print("-" * 80)
print("Cosine Similarity was used to compare the query")
print("with the TF-IDF vector of each document.")


print("\n" + "=" * 80)
print("                 FINAL SEARCH RANKING")
print("=" * 80)

for rank, (filename, score) in enumerate(ranked_results, start=1):
    print(
        f"{rank}. {filename:<45} "
        f"Score = {score:.6f}"
    )


print("\n" + "=" * 80)
print("                 MOST RELEVANT DOCUMENT")
print("=" * 80)

print(f"\nQuery: {query}")
print(f"Document: {most_relevant_document}")
print(f"Cosine Similarity: {highest_score:.6f}")


print("\n" + "=" * 80)
print("                      CONCLUSION")
print("=" * 80)

print("""
This Information Retrieval system processes five social-media
documents through preprocessing, tokenization, stopword removal,
and stemming.

Term Frequency (TF) was calculated to measure how frequently a
term occurs in each document.

Document Frequency (DF) was calculated to determine how many
documents contain each term.

Inverse Document Frequency (IDF) was calculated using:

IDF = log(N / DF)

TF-IDF was then calculated using:

TF-IDF = TF × IDF

The user can enter a search query, which is processed using the
same preprocessing steps. Query TF-IDF is calculated and cosine
similarity is used to compare the query with each document.

Finally, the documents are ranked according to their similarity
scores, and the document with the highest score is identified as
the most relevant document for the query.
""")

print("=" * 80)
print("                     COMPLETED SUCCESSFULLY")
print("=" * 80)

================================================================================
              INFORMATION RETRIEVAL SYSTEM
              FINAL SUMMARY
================================================================================

1. DOCUMENT COLLECTION
--------------------------------------------------------------------------------
Number of documents processed: 5
1. social_communication.txt
2. social_media_privacy_security.txt
3. social_media_education.txt
4. social_media_mental_health.txt
5. social_media_marketing.txt

2. PREPROCESSING
--------------------------------------------------------------------------------
✓ Lowercase conversion
✓ Punctuation and special-character removal
✓ Extra-space removal

3. TOKENIZATION
--------------------------------------------------------------------------------
✓ Documents divided into individual words

4. STOPWORD REMOVAL
--------------------------------------------------------------------------------
✓ Common English stopwords removed

5. STEMMING
--------------------------------------------------------------------------------
✓ Words converted to their stem forms using Porter Stemmer

6. TERM FREQUENCY (TF)
--------------------------------------------------------------------------------
Formula:
TF = Number of occurrences of term / Total number of terms
✓ TF calculated manually for all documents

7. DOCUMENT FREQUENCY (DF)
--------------------------------------------------------------------------------
Formula:
DF = Number of documents containing the term
✓ DF calculated for all terms

8. INVERSE DOCUMENT FREQUENCY (IDF)
--------------------------------------------------------------------------------
Formula:
IDF = log(N / DF)
Where N = 5
✓ IDF calculated manually

9. TF-IDF
--------------------------------------------------------------------------------
Formula:
TF-IDF = TF × IDF
✓ TF-IDF calculated manually for all 5 documents

10. USER QUERY
--------------------------------------------------------------------------------
Original Query:
privacy security social media

Processed Query:
['privaci', 'secur', 'social', 'media']

11. DOCUMENT RETRIEVAL
--------------------------------------------------------------------------------
Cosine Similarity was used to compare the query
with the TF-IDF vector of each document.

================================================================================
                 FINAL SEARCH RANKING
================================================================================
1. social_media_privacy_security.txt             Score = 0.259137
2. social_communication.txt                      Score = 0.056908
3. social_media_education.txt                    Score = 0.047003
4. social_media_mental_health.txt                Score = 0.000000
5. social_media_marketing.txt                    Score = 0.000000

================================================================================
                 MOST RELEVANT DOCUMENT
================================================================================

Query: privacy security social media
Document: social_media_privacy_security.txt
Cosine Similarity: 0.259137

================================================================================
                      CONCLUSION
================================================================================

This Information Retrieval system processes five social-media
documents through preprocessing, tokenization, stopword removal,
and stemming.

Term Frequency (TF) was calculated to measure how frequently a
term occurs in each document.

Document Frequency (DF) was calculated to determine how many
documents contain each term.

Inverse Document Frequency (IDF) was calculated using:

IDF = log(N / DF)

TF-IDF was then calculated using:

TF-IDF = TF × IDF

The user can enter a search query, which is processed using the
same preprocessing steps. Query TF-IDF is calculated and cosine
similarity is used to compare the query with each document.

Finally, the documents are ranked according to their similarity
scores, and the document with the highest score is identified as
the most relevant document for the query.

================================================================================
                     COMPLETED SUCCESSFULLY
================================================================================